name = "Lucky World Invasion"
author = "huanghui"
version = "2.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "376acbd109f66fcef41aad4704a8d17825439ebedbc8a99fecf08e80dc958571"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
