name = "Lucky World Invasion"
author = "huanghui"
version = "2.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb7d37abd5a48afdde3afe39a67a6b523201167dabdf404da7ec7dff56f5fc4a"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
