name = "Lucky World Invasion"
author = "huanghui"
version = "2.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8af226dab6f73183a5d864445e21b13ab955a136399832fdc3ffe7f39443b72"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
