State:6
Info:1.20.1, Forge 47.3.5
Logo:PCL\Logo.png
ReleaseTime:2024-07-06 05:45
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:47.3.5
VersionNeoForge:
VersionApiCode:47030005
VersionOriginal:1.20.1
VersionOriginalMain:20
VersionOriginalSub:1
VersionArgumentIndie:1
LogoCustom:True
